spring:
  application:
    name: todo-list-application
  datasource:
    url: jdbc:h2:file:C:/Users/HP/test;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: godwin
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true